# Generated by Django 2.2.1 on 2019-05-02 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_espe', models.CharField(max_length=3)),
                ('des_espe', models.TextField()),
                ('cod_esta', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paci', models.CharField(max_length=8)),
                ('ape_pate_paci', models.TextField()),
                ('ape_mate_paci', models.TextField()),
                ('nom_medi', models.TextField()),
                ('cod_cole_medi', models.CharField(max_length=18)),
                ('cod_rne', models.CharField(max_length=6)),
                ('num_tiem_cons', models.SmallIntegerField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_paci', models.CharField(max_length=8)),
                ('ape_pate_paci', models.TextField()),
                ('ape_mate_paci', models.TextField()),
                ('nom_paci', models.TextField()),
                ('fec_naci', models.DateTimeField()),
                ('cod_sexo', models.CharField(max_length=1)),
                ('cod_estadocivil', models.CharField(max_length=3)),
                ('cod_tipo_docu', models.CharField(max_length=2)),
                ('des_dni', models.CharField(max_length=15)),
                ('des_dire', models.TextField()),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_cita', models.DateTimeField()),
                ('cod_turn', models.CharField(max_length=1)),
                ('num_hora', models.CharField(max_length=10)),
                ('nom_paci', models.TextField()),
                ('cod_esta', models.CharField(max_length=1)),
                ('cod_tipo', models.CharField(max_length=1)),
                ('des_obse', models.TextField()),
                ('cod_usuario', models.CharField(max_length=8)),
                ('cod_tipo_docu', models.CharField(max_length=3)),
                ('cod_seri_docu', models.CharField(max_length=3)),
                ('num_docu', models.CharField(max_length=8)),
                ('epago_fecha_hora', models.DateTimeField()),
                ('epago_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cod_medi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.Medico')),
                ('cod_paci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.Paciente')),
            ],
        ),
    ]
