# Generated by Django 2.2.1 on 2019-05-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='num_cons_cita',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MedicoHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dia', models.CharField(max_length=1)),
                ('cod_turn', models.CharField(max_length=1)),
                ('num_hora_ingr', models.CharField(max_length=10)),
                ('num_hora_sali', models.CharField(max_length=10)),
                ('num_entr_cita', models.SmallIntegerField()),
                ('num_tiem_cons', models.SmallIntegerField()),
                ('num_cons_cita', models.SmallIntegerField()),
                ('cod_medi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.Medico')),
            ],
        ),
    ]
